modLoader = "javafml"
loaderVersion = "[37,)"
license = "AGPL v3"
[[mods]]
modId = "petphrasex"
version = "1.1.0"
displayName = "PetPhraseX-Client"
credits = ""
authors = "Tapio,HSSkyBoy"
description = "本模组添加了“口癖”功能——在玩家发出的消息末尾自动加上一段文字（默认为"  nya"，可于配置文件中自定义）"