name: Mod Build

on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        java: [21]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: 检查代码
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: 设置 AzuluOpenJDK 21
        uses: actions/setup-java@v3.6.0  # 检查是否有更新的版本
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: 给予 Gradle Wrapper 执行权限
        run: chmod +x ./gradlew

      - name: 设置构建缓存
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Gradle 构建
        run: ./gradlew build --info
        continue-on-error: false  # 根据需要决定是否添加此选项

      - name: 查找正确的 JAR
        id: find-jar
        run: |
          output=$(ls build/libs/*.jar | grep -v '-dev\|-sources' | head -1)
          echo "jarname=$output" >> $GITHUB_OUTPUT

      - name: 上传构建产物
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: PetPharseX-Fabric
          path: build/libs/