# 这个工作流将使用非GitHub认证的操作。
# 部分内容将由第三方提供，并且受到单独的服务条款、隐私政策和支持文档的约束。
# 这个工作流将构建一个Java项目，并使用Gradle缓存/恢复任何依赖项以提高工作流执行时间。
# 更多信息请查看：https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build Forge with Gradle

on:
  push:
    branches: [ "Forge1.19.2" ]
  workflow_dispatch: 

permissions:
  contents: read

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: 给予gradlew执行权限
      run: chmod +x gradlew

    - name: 使用Gradle构建项目
      run: ./gradlew build -PuseCommitHashInVersion

    - name: 上传构建产物
      uses: actions/upload-artifact@v3.1.2
      with:
        name: PetPharseX-Forge-1.19.2
        path: build/libs
        if-no-files-found: error
        compression-level: 8